### ISSUE TITLE
Create additional-resources page

### ISSUE THREAD

**Issue by denar90** [marionettejs/marionettejs.com#452]
### Todo
- [x] Update [awesome list](https://github.com/sadcitizen/awesome-marionette) with resources for main page
- [x] Parse topics from [awesome list](https://github.com/sadcitizen/awesome-marionette) file using grunt
- [x] Automatically generate data files for topics: Tutorials and articles, Books, Videos,Examples and boilerplates, Libraries
- [x] ~~Make data for `Books` topic the same structure as [books.json](https://github.com/marionettejs/marionettejs.com/blob/master/src/data/books.json)~~
- [x] Make data for `Videos` topic the same structure as [videos.json](https://github.com/marionettejs/marionettejs.com/blob/master/src/data/videos.json)
- [x] Create `examples.json` using github API.
- [x] Cut some resources from main page
- [x] Add links to "Additional resources page" on menu and other places
- [x] Add tests

**Comment by jdaudier** [comment]
Would be great to allow flexibility to exclude or add to the parsed list from Awesome list.

**Comment by denar90** [comment]
I've also been thinking to write some tests for compilers using [AVA](https://github.com/sindresorhus/ava). It really good works with promises. I've added some example for my compiler but soon we can cover all of them.

**Comment by denar90** [comment]
About `videos` file. After creating json from list we can send request and get youtube video data. But problem in format. Format for video described [here](https://github.com/marionettejs/marionettejs.com/blob/master/src/data/README.md) can't be reached by format which youtube provide with:
```javascipt
{
 "kind": "youtube#videoListResponse",
 "etag": "\"zekp1FB4kTkkM-rWc1qIAAt-BWc/YEXgZysUsYLiaQP-TsJ06g5fKic\"",
 "pageInfo": {
  "totalResults": 1,
  "resultsPerPage": 1
 },
 "items": [
  {
   "kind": "youtube#video",
   "etag": "\"zekp1FB4kTkkM-rWc1qIAAt-BWc/2vl2mbQ52e_OMWORgKaIpNlfrbA\"",
   "id": "jbGm3mJXh_s",
   "snippet": {
    "publishedAt": "2014-12-17T17:11:38.000Z",
    "channelId": "UCQUPI1PxfE4-bqwuI26I2HA",
    "title": "Jason Laster - Backbone under the Magnifying Glass Tools for Exploring and Debugging Your Apps",
    "description": "",
    "thumbnails": {
     "default": {
      "url": "https://i.ytimg.com/vi/jbGm3mJXh_s/default.jpg",
      "width": 120,
      "height": 90
     },
     "medium": {
      "url": "https://i.ytimg.com/vi/jbGm3mJXh_s/mqdefault.jpg",
      "width": 320,
      "height": 180
     },
     "high": {
      "url": "https://i.ytimg.com/vi/jbGm3mJXh_s/hqdefault.jpg",
      "width": 480,
      "height": 360
     },
     "standard": {
      "url": "https://i.ytimg.com/vi/jbGm3mJXh_s/sddefault.jpg",
      "width": 640,
      "height": 480
     },
     "maxres": {
      "url": "https://i.ytimg.com/vi/jbGm3mJXh_s/maxresdefault.jpg",
      "width": 1280,
      "height": 720
     }
    },
    "channelTitle": "BocoupLLC",
    "tags": [
     "Open Web",
     "JavaScript",
     "Programming",
     "Open Source",
     "Bocoup"
    ],
    "categoryId": "28",
    "liveBroadcastContent": "none",
    "localized": {
     "title": "Jason Laster - Backbone under the Magnifying Glass Tools for Exploring and Debugging Your Apps",
     "description": ""
    }
   }
  }
 ]
}


```

Can I change format a bit due to youtube API ?

**Comment by peterblazejewicz** [comment]
@denar90 
Yes, you can I think. The format (and data description/names) does not matter. What matters is to be sure that data from JSON is outputted to static html markup. We just use this information to enhance crawlers and screen readers (so Marionette has good generic traffic from the net)

**Comment by denar90** [comment]
@peterblazejewicz Can moving some sections (books, videos. example apps) from main page to additional resources page have bad effect on traffic?

**Comment by peterblazejewicz** [comment]
> Can moving some sections (books, videos. example apps) from main page to additional resources page have bad effect on traffic?

No (if done while preserving markup and document outline/sections). Just go ahead and it could be later reviewed.
btw: that's about library discoverability - not traffic :)
Thanks!

**Comment by denar90** [comment]
What do you think about using our own awesome list? We can make fork of original one and prepare format what we need. Because in some places instead of line 
`A Thorough Introduction To Backbone.Marionette by Joseph Zimmerman - [Part 1](some_link), [Part 2](some_link) and [Part 3](some_link)`
we should parse lines like
```
 [A Thorough Introduction To Backbone.Marionette by Joseph Zimmerman, Part 1](some_link)
 [A Thorough Introduction To Backbone.Marionette by Joseph Zimmerman, Part 2](some_link)
 [A Thorough Introduction To Backbone.Marionette by Joseph Zimmerman, Part 3](some_link)
```
Or in original repo we can try to change contributing instructions so format will support our needs (compiler needs).

**Comment by peterblazejewicz** [comment]
> A Thorough Introduction To Backbone.Marionette by Joseph Zimmerman - [Part 1](some_link), [Part 2](some_link) and [Part 3](some_link)

Splitting or rewriting this could be an overkill - the Google or Bing are smart enough to crawl a real meaning/title of the link I believe - the link's target origin content heading/page is important (their relevance to the link source, uniqueness, etc)

**Comment by denar90** [comment]
Sorry, I've read [contributing](https://github.com/sadcitizen/awesome-marionette/blob/master/contributing.md) 
> Use the following format: [List Name](link)

Maybe list was made before [awesome contributing](https://github.com/sindresorhus/awesome/blob/master/contributing.md#adding-to-this-list) file was changed, so task 
>Update awesome list with resources for main page

became more interesting)

**Comment by denar90** [comment]
merged #453
